### ISSUE TITLE
Files in volumes are written as root

### ISSUE THREAD

**Issue by kivS** [bfirsh/whalebrew#11]
When installing npm packages they get written as root, any recommended way to 'inherit ownership'?

Thanks

**Comment by bfirsh** [comment]
Hmm - thanks for the report. I don't think there is a simple way to solve this.

The solution, I think, is for Whalebrew to [create a local volume and use the uid and gid options](https://docs.docker.com/engine/reference/commandline/volume_create/) to map them correctly to the host uid and gid.

**Comment by bfirsh** [comment]
@kivS Fixed in 0.0.4!
