### ISSUE TITLE
post use cases in the readme

### ISSUE THREAD

**Issue by deltaskelta** [bfirsh/whalebrew#13]
I saw the repo and it looks interesting but I cant see a practical reason for its use. 

Is it just to avoid dependency issues?

**Comment by xyproto** [comment]
If you think of docker images as "universal server executables" it sorta makes sense. You can run the exact same "executable" regardless of the underlying operating system. But yeah, I would also like to see some actual use cases.

**Comment by bfirsh** [comment]
Yeah, good point it's not very clear *why* it is useful. It's particularly good for stuff with horrendous dependencies: https://mobile.twitter.com/bfirsh/status/824688876056895489
