### ISSUE TITLE
Enhancement: sync_blob_args

### ISSUE THREAD

**Issue by LongLiveCHIEF** [bfirsh/whalebrew#21]
Currently, `whalebrew` compatible images can only work with images that only alter one directory (`/workdir`). However, this makes packages such as the [rsync merge I retracted](https://github.com/whalebrew/whalebrew-packages/pull/5) impossible to utilize. I have an Idea on how to make this work.

## Whalebrew Spec Proposal: Blob arg handling 

In order to make packages that may work with more than 1 directory, for example `rsync`, implementing Dockerfiles must:

- add the `io.whalebrew.options.sync_blob_args`
- create a `/syncdir` in the image
- Add the `/syncdir` as a volume in your `Dockerfile`

Implementing additional mounts during command executing:

- the `/usr/local/bin` command will take any blobs given as args after the named command, and map the corresponding host volumes to `/syncdir/hostvolume`

## Challenges

- Would we need to add a way for package creators to specify a delimeter?
- Would this satisfy images that require host device access?

**Comment by bfirsh** [comment]
Thanks for the suggestion. I'm not sure I fully understand what you're trying to achieve, though. Can you give an example of what you're trying to do?

**Comment by LongLiveCHIEF** [comment]
sure:

This would currently fail:
```
$ mkdir $HOME/tmp1 $HOME/tmp2
$ echo "hello world" > $HOME/tmp1/hello.txt
$ whalebrew install longlivechief/rsyncd
$ rsyncd ~$HOME/tmp1/ $HOME/tmp2
$ ll $HOME/tmp2
(empty)
```

**Comment by LongLiveCHIEF** [comment]
closing in favor of #22
