### ISSUE TITLE
Ask permission from user to mount volumes and pass environment variables

### ISSUE THREAD

**Issue by bfirsh** [bfirsh/whalebrew#23]
The `io.whalebrew.config.volumes` and `io.whalebrew.config.environment` labels allow images to request volumes and envvars to be passed to the container at runtime. Since we allow installing arbitrary Docker images, this is potentially a vector for attack.

Arguably, this is similar to the risk of just running normal command-line commands, but because we are sandboxing things anyway, let's do what sandboxes do well and have granular permissions!

When a package with these labels is installed, Whalebrew should ask the user if it all looks okay before installing:

    $ whalebrew install oscorp/kittens
    Pulling oscorp/kittens...
    ...
    This package needs additional access to your system. It wants to:
    * Mount the directory /etc/passwd
    * Read the environment variable AWS_ACCESS_KEY
    * Read the environment variable AWS_SECRET
    Is this okay? y/n (y)

**Comment by nithin-bose** [comment]
Close the issue?? Or is something pending??

**Comment by bfirsh** [comment]
Nope thanks!
