### ISSUE TITLE
unknown command "upgrade" for "whalebrew"

### ISSUE THREAD

**Issue by willie** [bfirsh/whalebrew#3]
On OS X:

Installed via: `curl -L "https://github.com/bfirsh/whalebrew/releases/download/0.0.1/whalebrew-$(uname -s)-$(uname -m)" -o /usr/local/bin/whalebrew; chmod +x /usr/local/bin/whalebrew
`

returns this error: `unknown command "upgrade" for "whalebrew"`

**Comment by willie** [comment]
Sorry, failed to mention the command after install: `whalebrew upgrade`

**Comment by bfirsh** [comment]
Oops, yes, that was some optimistic readme-driven development there, and I never got round to implementing it. :)

Just `docker pull` the image -- that'll upgrade the package.
