### ISSUE TITLE
open /usr/local/bin/jamf: permission denied

### ISSUE THREAD

**Issue by mastertinner** [bfirsh/whalebrew#30]
I can install and run whalebrew commands with no problem. When I run `whalebrew list`, however, I get `open /usr/local/bin/jamf: permission denied`. I'm running macOS Sierra 10.12.2 (Darwin Kernel Version 16.3.0) and Docker for Mac 1.13.0.

**Comment by bfirsh** [comment]
Thanks for the report! Dupe of #7.

**Comment by mastertinner** [comment]
Thanks for the quick fix, @bfirsh! You are awesome! (and sorry for the dupe!)
