### ISSUE TITLE
Operation not permitted error.

### ISSUE THREAD

**Issue by collegeimprovements** [bfirsh/whalebrew#5]
I keep getting the following error even when I run the installation script with `sudo` access.

`chmod: changing permissions of '/usr/local/bin/whalebrew': Operation not permitted`

**Comment by collegeimprovements** [comment]
After manually setting permissions with chmod it worked.

**Comment by waeltken** [comment]
You need to upgrade your docker-machine or docker deamon:

> $ whalebrew search
> Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.24)

If youre running docker-machine on a mac I suggest you to upgrade your machine by running:

> $ docker-machine ls                                                                                                                                                                                                                                                                                                  
> NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
> default   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.6

and then upgrade your docker-machine with the according command:

> $ docker-machine upgrade default
> Waiting for SSH to be available...
> Detecting the provisioner...
> Upgrading docker...
> Stopping machine to do the upgrade...
> Upgrading machine "default"..
> ....

After this procedure whalebrew should run as expected:

> $ whalebrew search
> whalebrew/ack
> whalebrew/awscli
> whalebrew/docker-cloud
> whalebrew/ffmpeg
> whalebrew/gnupg
> whalebrew/httpie
> whalebrew/hyper
> whalebrew/imagemagick
> whalebrew/irssi
> ...

**Comment by vFlagR** [comment]
Having the exact same issue. Running Ubuntu 16.04, tried updating to the latest version of Docker but that's not helped.

**Comment by bfirsh** [comment]
@collegeimprovements @vFlagR what's the output of `docker version`?

**Comment by uolot** [comment]
@bfirsh I am experiencing the same problem, here's my log:

```bash
$ whalebrew search 
Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.24)

$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64
                                             
Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3                       
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64

```

**Comment by bfirsh** [comment]
Ah right, yes. This is a simple issue - we just need to set a lower API version for the client. We don't need such a recent version for searching images.

The solution in the meantime, as suggested above, is to just upgrade your version of Docker to 1.13.
