### ISSUE TITLE
Configure image so homebrew runs without -it?

### ISSUE THREAD

**Issue by szeck87** [bfirsh/whalebrew#61]
This is a clarification and a question.  From the readme here, it looks like the following is basically what is run when a Docker image is installed through Whalebrew and run:  `docker run -it -v "$(pwd)":/workdir -w /workdir $IMAGE "$@"`, as in it will always include `-it`, correct?

I'm trying to work through an [issue](https://forums.docker.com/t/docker-image-wont-run-with-t/38733) where the Docker image doesn't work properly when `-t` is included for pseudo-TTY.  So I'm thinking that's why it also doesn't work when installing/running through Whalebrew.  While I work through that issue, Is there a way to configure the Dockerfile so Whalebrew does not include `-it`?

**Comment by themalkolm** [comment]
You always get -i. You get -t only if you are in a terminal.

https://github.com/bfirsh/whalebrew/blob/master/cmd/run.go

**Comment by szeck87** [comment]
Thank you.

**Comment by themalkolm** [comment]
It shouldn't be a big deal to add support for noninteractive or and nontty containers if you need it.

**Comment by szeck87** [comment]
It's ok, I think I found the issue with the image.  Thanks though.
