### ISSUE TITLE
Is WhaleBrew compatible with Docker Toolbox on the Apple Mac

### ISSUE THREAD

**Issue by carlca** [bfirsh/whalebrew#62]
Apple Mac Pro (early 2009) Firmware 4.1->5.1
macOS 10.13.1 High Sierra
Docker Toolbox version 17.10.0-ce, build f4ffd25

Hello, I have an ancient but powerful Apple Mac Pro which, apparently is too old to run Docker for Mac. It does run the earlier Docker Toolbox though. Is WhaleBrew compatible with Docker Toolbox?

**Comment by bfirsh** [comment]
Yeah, probably! Have you tried it?

**Comment by carlca** [comment]
Not yet. I was trying to be cautious!

**Comment by grokkingStuff** [comment]
@carlca, mind closing the issue?
