### ISSUE TITLE
Listing packages breaks when it does not have permission to read a file

### ISSUE THREAD

**Issue by jeroenjanssens** [bfirsh/whalebrew#7]
On macOS I get the following message:

```bash
$ whalebrew list
read /usr/local/bin/__pycache__: is a directory
```

Everything else appears to be working correctly. Is there any additional information I could provide to help resolve this issue?

**Comment by Herkemer** [comment]
I'm seeing a similar error on a different file.  It's actually a link to a file but my user does not have read permissions on that file.

open /usr/local/bin/foo: permission denied

I suspect something in IsPackage is getting confused by this permissions issue.

**Comment by bfirsh** [comment]
Going to leave this open, because it should also handle permission errrors.
